name: Claude Code AI Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-code:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      github.event_name == 'issues' ||
      github.event_name == 'pull_request'
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Claude Code for Issue Comments
        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            User comment from issue #${{ github.event.issue.number }}:
            ${{ github.event.comment.body }}
            
            Please analyze the request and provide assistance. If this requires code changes, implement them.
          anthropic_api_key: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          model: claude-3-5-sonnet-20241022
          max_turns: 10
          timeout_minutes: 30
          allowed_tools: "Bash,Read,Write,Edit,MultiEdit,Glob,Grep,LS"

      - name: Run Claude Code for PR Comments
        if: github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            User comment on PR #${{ github.event.pull_request.number }}:
            ${{ github.event.comment.body }}
            
            Context: This comment was made on a pull request. Please review the relevant code changes and provide assistance.
          anthropic_api_key: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          model: claude-3-5-sonnet-20241022
          max_turns: 10
          timeout_minutes: 30
          allowed_tools: "Bash,Read,Write,Edit,MultiEdit,Glob,Grep,LS"

      - name: Run Claude Code for New Issues
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            New issue opened: ${{ github.event.issue.title }}
            
            Issue description:
            ${{ github.event.issue.body }}
            
            Please analyze this issue and provide initial guidance or implementation if appropriate.
          anthropic_api_key: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          model: claude-3-5-sonnet-20241022
          max_turns: 10
          timeout_minutes: 30
          allowed_tools: "Bash,Read,Write,Edit,MultiEdit,Glob,Grep,LS"

      - name: Run Claude Code for PR Reviews
        if: github.event_name == 'pull_request'
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            Please review this pull request:
            Title: ${{ github.event.pull_request.title }}
            Description: ${{ github.event.pull_request.body }}
            
            Analyze the code changes and provide feedback on code quality, potential issues, and suggestions for improvement.
          anthropic_api_key: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          model: claude-3-5-sonnet-20241022
          max_turns: 5
          timeout_minutes: 20
          allowed_tools: "Bash(git diff),Read,Glob,Grep,LS"

      - name: Commit and push changes
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action (Claude)"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Claude Code automated changes

            Triggered by: ${{ github.event_name }}
            
            Co-authored-by: Claude <claude@anthropic.com>"
            git push
          fi